In [1]:
from pathlib import Path
from collections import defaultdict

import polars as pl

In [2]:
PLAYER_DIR = Path("data/player_hands")
ACTION_DIR = Path("data/actions")

MIN_HANDS = 500
MIN_3BET_OPPORTUNITIES = 100

In [3]:
stats = defaultdict(lambda: {
    "hands": 0,
    "three_bet_opportunities": 0,
    "three_bets": 0,
})

In [6]:

action_files = sorted(
    ACTION_DIR.glob("actions_*.parquet")
)

print(f"Found {len(action_files):,} action files")

Found 218 action files

In [7]:
for file_index, action_file in enumerate(action_files, start=1):

    chunk_id = action_file.stem.replace("actions_", "")

    player_file = (
        PLAYER_DIR /
        f"player_hands_{chunk_id}.parquet"
    )

    if not player_file.exists():
        print(f"Missing player file for {action_file.name}")
        continue

    print(
        f"[{file_index}/{len(action_files)}] "
        f"Processing chunk {chunk_id}"
    )

    # Load only needed columns
    players = pl.read_parquet(
        player_file,
        columns=[
            "hand_id",
            "player_id",
            "player_number",
        ],
    )

    actions = pl.read_parquet(
        action_file,
        columns=[
            "hand_id",
            "action_number",
            "raw_action",
        ],
    )

    # Count hands per player
    hand_counts = (
        players
        .group_by("player_id")
        .agg(
            pl.len().alias("hands")
        )
    )

    for player_id, hands in hand_counts.iter_rows():

        if player_id is not None:
            stats[player_id]["hands"] += hands

    # Map (hand_id, player_number) -> player_id
    player_lookup = {}

    for row in players.iter_rows(named=True):

        player_lookup[
            (
                row["hand_id"],
                row["player_number"],
            )
        ] = row["player_id"]

    # Group actions by hand
    hand_actions = (
        actions
        .sort([
            "hand_id",
            "action_number",
        ])
        .group_by(
            "hand_id",
            maintain_order=True,
        )
        .agg(
            pl.col("raw_action")
        )
    )

    # Identify 3-bet opportunities and 3-bets
    for hand_id, action_list in hand_actions.iter_rows():

        raises = 0

        for raw_action in action_list:

            parts = raw_action.split()

            if len(parts) < 2:
                continue

            # Flop dealt, so preflop is finished
            if parts[0] == "d" and parts[1] == "db":
                break

            # Ignore non-player actions
            if not parts[0].startswith("p"):
                continue

            try:
                player_number = int(parts[0][1:])
            except ValueError:
                continue

            action_type = parts[1]

            # First raise = open raise
            if action_type == "cbr" and raises == 0:
                raises = 1
                continue

            # After open raise, fold/call/raise all count
            # as a 3-bet opportunity
            if raises == 1 and action_type in {
                "f",
                "cc",
                "cbr",
            }:

                player_id = player_lookup.get(
                    (
                        hand_id,
                        player_number,
                    )
                )

                if player_id is None:
                    continue

                stats[player_id][
                    "three_bet_opportunities"
                ] += 1

                # Second raise = 3-bet
                if action_type == "cbr":

                    stats[player_id][
                        "three_bets"
                    ] += 1

                    # Anything after this would be
                    # facing a 3-bet, not an open raise
                    break

[1/218] Processing chunk 0000
[2/218] Processing chunk 0001
[3/218] Processing chunk 0002
[4/218] Processing chunk 0003
[5/218] Processing chunk 0004
[6/218] Processing chunk 0005
[7/218] Processing chunk 0006
[8/218] Processing chunk 0007
[9/218] Processing chunk 0008
[10/218] Processing chunk 0009
[11/218] Processing chunk 0010
[12/218] Processing chunk 0011
[13/218] Processing chunk 0012
[14/218] Processing chunk 0013
[15/218] Processing chunk 0014
[16/218] Processing chunk 0015
[17/218] Processing chunk 0016
[18/218] Processing chunk 0017
[19/218] Processing chunk 0018
[20/218] Processing chunk 0019
[21/218] Processing chunk 0020
[22/218] Processing chunk 0021
[23/218] Processing chunk 0022
[24/218] Processing chunk 0023
[25/218] Processing chunk 0024
[26/218] Processing chunk 0025
[27/218] Processing chunk 0026
[28/218] Processing chunk 0027
[29/218] Processing chunk 0028
[30/218] Processing chunk 0029
[31/218] Processing chunk 0030
[32/218] Processing chunk 0031
[33/218] Processing chunk 0032
[34/218] Processing chunk 0033
[35/218] Processing chunk 0034
[36/218] Processing chunk 0035
[37/218] Processing chunk 0036
[38/218] Processing chunk 0037
[39/218] Processing chunk 0038
[40/218] Processing chunk 0039
[41/218] Processing chunk 0040
[42/218] Processing chunk 0041
[43/218] Processing chunk 0042
[44/218] Processing chunk 0043
[45/218] Processing chunk 0044
[46/218] Processing chunk 0045
[47/218] Processing chunk 0046
[48/218] Processing chunk 0047
[49/218] Processing chunk 0048
[50/218] Processing chunk 0049
[51/218] Processing chunk 0050
[52/218] Processing chunk 0051
[53/218] Processing chunk 0052
[54/218] Processing chunk 0053
[55/218] Processing chunk 0054
[56/218] Processing chunk 0055
[57/218] Processing chunk 0056
[58/218] Processing chunk 0057
[59/218] Processing chunk 0058
[60/218] Processing chunk 0059
[61/218] Processing chunk 0060
[62/218] Processing chunk 0061
[63/218] Processing chunk 0062
[64/218] Processing chunk 0063
[65/218] Processing chunk 0064
[66/218] Processing chunk 0065
[67/218] Processing chunk 0066
[68/218] Processing chunk 0067
[69/218] Processing chunk 0068
[70/218] Processing chunk 0069
[71/218] Processing chunk 0070
[72/218] Processing chunk 0071
[73/218] Processing chunk 0072
[74/218] Processing chunk 0073
[75/218] Processing chunk 0074
[76/218] Processing chunk 0075
[77/218] Processing chunk 0076
[78/218] Processing chunk 0077
[79/218] Processing chunk 0078
[80/218] Processing chunk 0079
[81/218] Processing chunk 0080
[82/218] Processing chunk 0081
[83/218] Processing chunk 0082
[84/218] Processing chunk 0083
[85/218] Processing chunk 0084
[86/218] Processing chunk 0085
[87/218] Processing chunk 0086
[88/218] Processing chunk 0087
[89/218] Processing chunk 0088
[90/218] Processing chunk 0089
[91/218] Processing chunk 0090
[92/218] Processing chunk 0091
[93/218] Processing chunk 0092
[94/218] Processing chunk 0093
[95/218] Processing chunk 0094
[96/218] Processing chunk 0095
[97/218] Processing chunk 0096
[98/218] Processing chunk 0097
[99/218] Processing chunk 0098
[100/218] Processing chunk 0099
[101/218] Processing chunk 0100
[102/218] Processing chunk 0101
[103/218] Processing chunk 0102
[104/218] Processing chunk 0103
[105/218] Processing chunk 0104
[106/218] Processing chunk 0105
[107/218] Processing chunk 0106
[108/218] Processing chunk 0107
[109/218] Processing chunk 0108
[110/218] Processing chunk 0109
[111/218] Processing chunk 0110
[112/218] Processing chunk 0111
[113/218] Processing chunk 0112
[114/218] Processing chunk 0113
[115/218] Processing chunk 0114
[116/218] Processing chunk 0115
[117/218] Processing chunk 0116
[118/218] Processing chunk 0117
[119/218] Processing chunk 0118
[120/218] Processing chunk 0119
[121/218] Processing chunk 0120
[122/218] Processing chunk 0121
[123/218] Processing chunk 0122
[124/218] Processing chunk 0123
[125/218] Processing chunk 0124
[126/218] Processing chunk 0125
[127/218] Processing chunk 0126
[128/218] Processing chunk 0127
[129/218] Processing chunk 0128
[130/218] Processing chunk 0129
[131/218] Processing chunk 0130
[132/218] Processing chunk 0131
[133/218] Processing chunk 0132
[134/218] Processing chunk 0133
[135/218] Processing chunk 0134
[136/218] Processing chunk 0135
[137/218] Processing chunk 0136
[138/218] Processing chunk 0137
[139/218] Processing chunk 0138
[140/218] Processing chunk 0139
[141/218] Processing chunk 0140
[142/218] Processing chunk 0141
[143/218] Processing chunk 0142
[144/218] Processing chunk 0143
[145/218] Processing chunk 0144
[146/218] Processing chunk 0145
[147/218] Processing chunk 0146
[148/218] Processing chunk 0147
[149/218] Processing chunk 0148
[150/218] Processing chunk 0149
[151/218] Processing chunk 0150
[152/218] Processing chunk 0151
[153/218] Processing chunk 0152
[154/218] Processing chunk 0153
[155/218] Processing chunk 0154
[156/218] Processing chunk 0155
[157/218] Processing chunk 0156
[158/218] Processing chunk 0157
[159/218] Processing chunk 0158
[160/218] Processing chunk 0159
[161/218] Processing chunk 0160
[162/218] Processing chunk 0161
[163/218] Processing chunk 0162
[164/218] Processing chunk 0163
[165/218] Processing chunk 0164
[166/218] Processing chunk 0165
[167/218] Processing chunk 0166
[168/218] Processing chunk 0167
[169/218] Processing chunk 0168
[170/218] Processing chunk 0169
[171/218] Processing chunk 0170
[172/218] Processing chunk 0171
[173/218] Processing chunk 0172
[174/218] Processing chunk 0173
[175/218] Processing chunk 0174
[176/218] Processing chunk 0175
[177/218] Processing chunk 0176
[178/218] Processing chunk 0177
[179/218] Processing chunk 0178
[180/218] Processing chunk 0179
[181/218] Processing chunk 0180
[182/218] Processing chunk 0181
[183/218] Processing chunk 0182
[184/218] Processing chunk 0183
[185/218] Processing chunk 0184
[186/218] Processing chunk 0185
[187/218] Processing chunk 0186
[188/218] Processing chunk 0187
[189/218] Processing chunk 0188
[190/218] Processing chunk 0189
[191/218] Processing chunk 0190
[192/218] Processing chunk 0191
[193/218] Processing chunk 0192
[194/218] Processing chunk 0193
[195/218] Processing chunk 0194
[196/218] Processing chunk 0195
[197/218] Processing chunk 0196
[198/218] Processing chunk 0197
[199/218] Processing chunk 0198
[200/218] Processing chunk 0199
[201/218] Processing chunk 0200
[202/218] Processing chunk 0201
[203/218] Processing chunk 0202
[204/218] Processing chunk 0203
[205/218] Processing chunk 0204
[206/218] Processing chunk 0205
[207/218] Processing chunk 0206
[208/218] Processing chunk 0207
[209/218] Processing chunk 0208
[210/218] Processing chunk 0209
[211/218] Processing chunk 0210
[212/218] Processing chunk 0211
[213/218] Processing chunk 0212
[214/218] Processing chunk 0213
[215/218] Processing chunk 0214
[216/218] Processing chunk 0215
[217/218] Processing chunk 0216
[218/218] Processing chunk 0217

In [8]:
rows = []

for player_id, values in stats.items():

    opportunities = values[
        "three_bet_opportunities"
    ]

    three_bets = values[
        "three_bets"
    ]

    three_bet_pct = (
        three_bets / opportunities * 100
        if opportunities > 0
        else None
    )

    rows.append({
        "player_id": player_id,
        "hands": values["hands"],
        "three_bet_opportunities": opportunities,
        "three_bets": three_bets,
        "three_bet_pct": three_bet_pct,
    })

player_stats = pl.DataFrame(rows)

player_stats.head()

shape: (5, 5)
┌────────────────────────┬───────┬─────────────────────────┬────────────┬───────────────┐
│ player_id              ┆ hands ┆ three_bet_opportunities ┆ three_bets ┆ three_bet_pct │
│ ---                    ┆ ---   ┆ ---                     ┆ ---        ┆ ---           │
│ str                    ┆ i64   ┆ i64                     ┆ i64        ┆ f64           │
╞════════════════════════╪═══════╪═════════════════════════╪════════════╪═══════════════╡
│ 6hXAotOLYqvlXW0qhMu1HA ┆ 138   ┆ 45                      ┆ 2          ┆ 4.444444      │
│ 2ePSN+HLDWDaDyFe0b2fYg ┆ 464   ┆ 129                     ┆ 1          ┆ 0.775194      │
│ wjAHhXRJQJvcZCPXAvJGfg ┆ 663   ┆ 225                     ┆ 15         ┆ 6.666667      │
│ Mhiwb9IWT0lQh96p/n5VHw ┆ 7     ┆ 3                       ┆ 0          ┆ 0.0           │
│ bhsTNSwYevCwt8Re1HktfA ┆ 118   ┆ 47                      ┆ 3          ┆ 6.382979      │
└────────────────────────┴───────┴─────────────────────────┴────────────┴───────────────┘

In [9]:
eligible = (
    player_stats
    .filter(
        (pl.col("hands") >= MIN_HANDS)
        &
        (
            pl.col("three_bet_opportunities")
            >= MIN_3BET_OPPORTUNITIES
        )
    )
    .sort(
        "three_bet_pct",
        descending=True,
    )
)

print("Total players:", player_stats.height)
print("Eligible players:", eligible.height)

eligible.head(20)

Total players: 278149
Eligible players: 34252

shape: (20, 5)
┌────────────────────────┬───────┬─────────────────────────┬────────────┬───────────────┐
│ player_id              ┆ hands ┆ three_bet_opportunities ┆ three_bets ┆ three_bet_pct │
│ ---                    ┆ ---   ┆ ---                     ┆ ---        ┆ ---           │
│ str                    ┆ i64   ┆ i64                     ┆ i64        ┆ f64           │
╞════════════════════════╪═══════╪═════════════════════════╪════════════╪═══════════════╡
│ Rg+i50SS6+QeSQgE2FImPA ┆ 1557  ┆ 562                     ┆ 273        ┆ 48.576512     │
│ mhifGhGiCbuMZM2R1vktCw ┆ 1835  ┆ 557                     ┆ 263        ┆ 47.217235     │
│ AKyZn/1VZB+f9UIwtf2x2w ┆ 563   ┆ 223                     ┆ 101        ┆ 45.29148      │
│ nJvYkAx04n101FyZf2GerQ ┆ 511   ┆ 161                     ┆ 70         ┆ 43.478261     │
│ Zw3PjbL5JbMOXl36usuX/w ┆ 574   ┆ 151                     ┆ 63         ┆ 41.721854     │
│ …                      ┆ …     ┆ …                       ┆ …          ┆ …             │
│ Lj1vXbOwCHCXVxzOfXgyJw ┆ 516   ┆ 196                     ┆ 70         ┆ 35.714286     │
│ e/USI/aiy+oD1YNAsbogaQ ┆ 660   ┆ 171                     ┆ 61         ┆ 35.672515     │
│ X4cAThyaVSJoJGgHhx4wKQ ┆ 892   ┆ 310                     ┆ 110        ┆ 35.483871     │
│ BecpLvSTkcSB3QZ1XuXhEg ┆ 2405  ┆ 374                     ┆ 132        ┆ 35.294118     │
│ zWuUDU+X6tqYsj7ZZNnsWw ┆ 718   ┆ 216                     ┆ 76         ┆ 35.185185     │
└────────────────────────┴───────┴─────────────────────────┴────────────┴───────────────┘

In [10]:
summary = eligible.select([

    pl.len().alias(
        "eligible_players"
    ),

    pl.col("three_bet_pct")
    .mean()
    .alias("mean_player_3bet_pct"),

    pl.col("three_bet_pct")
    .median()
    .alias("median_player_3bet_pct"),

    pl.col("three_bet_pct")
    .std()
    .alias("std_player_3bet_pct"),

    pl.col("three_bet_pct")
    .quantile(0.25)
    .alias("q25_3bet_pct"),

    pl.col("three_bet_pct")
    .quantile(0.75)
    .alias("q75_3bet_pct"),
])

summary

shape: (1, 6)
┌─────────────────┬────────────────┬────────────────┬────────────────┬──────────────┬──────────────┐
│ eligible_player ┆ mean_player_3b ┆ median_player_ ┆ std_player_3be ┆ q25_3bet_pct ┆ q75_3bet_pct │
│ s               ┆ et_pct         ┆ 3bet_pct       ┆ t_pct          ┆ ---          ┆ ---          │
│ ---             ┆ ---            ┆ ---            ┆ ---            ┆ f64          ┆ f64          │
│ u32             ┆ f64            ┆ f64            ┆ f64            ┆              ┆              │
╞═════════════════╪════════════════╪════════════════╪════════════════╪══════════════╪══════════════╡
│ 34252           ┆ 5.006977       ┆ 4.091183       ┆ 4.003817       ┆ 2.352941     ┆ 6.484432     │
└─────────────────┴────────────────┴────────────────┴────────────────┴──────────────┴──────────────┘

In [11]:
pooled = eligible.select(

    (
        pl.col("three_bets").sum()
        /
        pl.col(
            "three_bet_opportunities"
        ).sum()
        * 100
    )
    .alias("pooled_3bet_pct")

)

pooled

shape: (1, 1)
┌─────────────────┐
│ pooled_3bet_pct │
│ ---             │
│ f64             │
╞═════════════════╡
│ 5.508127        │
└─────────────────┘

In [12]:
thresholds = [100, 250, 500, 1000]

for threshold in thresholds:

    filtered = player_stats.filter(
        (pl.col("hands") >= 500)
        &
        (pl.col("three_bet_opportunities") >= threshold)
    )

    result = filtered.select([
        pl.len().alias("players"),

        pl.col("three_bet_pct")
        .mean()
        .alias("mean_3bet"),

        pl.col("three_bet_pct")
        .median()
        .alias("median_3bet"),

        pl.col("three_bet_pct")
        .quantile(0.25)
        .alias("q25"),

        pl.col("three_bet_pct")
        .quantile(0.75)
        .alias("q75"),
    ])

    print(f"\nMinimum opportunities: {threshold}")
    print(result)

Minimum opportunities: 100
shape: (1, 5)
┌─────────┬───────────┬─────────────┬──────────┬──────────┐
│ players ┆ mean_3bet ┆ median_3bet ┆ q25      ┆ q75      │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---      │
│ u32     ┆ f64       ┆ f64         ┆ f64      ┆ f64      │
╞═════════╪═══════════╪═════════════╪══════════╪══════════╡
│ 34252   ┆ 5.006977  ┆ 4.091183    ┆ 2.352941 ┆ 6.484432 │
└─────────┴───────────┴─────────────┴──────────┴──────────┘

Minimum opportunities: 250
shape: (1, 5)
┌─────────┬───────────┬─────────────┬──────────┬──────────┐
│ players ┆ mean_3bet ┆ median_3bet ┆ q25      ┆ q75      │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---      │
│ u32     ┆ f64       ┆ f64         ┆ f64      ┆ f64      │
╞═════════╪═══════════╪═════════════╪══════════╪══════════╡
│ 24847   ┆ 5.092938  ┆ 4.22833     ┆ 2.513966 ┆ 6.594154 │
└─────────┴───────────┴─────────────┴──────────┴──────────┘

Minimum opportunities: 500
shape: (1, 5)
┌─────────┬───────────┬─────────────┬──────────┬──────────┐
│ players ┆ mean_3bet ┆ median_3bet ┆ q25      ┆ q75      │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---      │
│ u32     ┆ f64       ┆ f64         ┆ f64      ┆ f64      │
╞═════════╪═══════════╪═════════════╪══════════╪══════════╡
│ 13449   ┆ 5.279914  ┆ 4.558459    ┆ 2.853067 ┆ 6.820567 │
└─────────┴───────────┴─────────────┴──────────┴──────────┘

Minimum opportunities: 1000
shape: (1, 5)
┌─────────┬───────────┬─────────────┬──────────┬──────────┐
│ players ┆ mean_3bet ┆ median_3bet ┆ q25      ┆ q75      │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---      │
│ u32     ┆ f64       ┆ f64         ┆ f64      ┆ f64      │
╞═════════╪═══════════╪═════════════╪══════════╪══════════╡
│ 7116    ┆ 5.505593  ┆ 4.964349    ┆ 3.166667 ┆ 7.112069 │
└─────────┴───────────┴─────────────┴──────────┴──────────┘